//Title: Game.h
//Author: Jeremy Dixon
//Date: 9/16/2025
//Description: This is part of the project in CMSC 202.
// This is the base project header file

//Do not edit this file
#ifndef GAME_H
#define GAME_H

#include "Unit.h"
#include "Squad.h"
#include <iostream>
#include <fstream>
#include <cstdlib>
#include <ctime>
#include <string>
using namespace std;

class Game {
 public:
  // Name - Game()
  // Desc - Constructs a new Game object and seeds random number generator
  // Preconditions - None
  // Postconditions - Game object created, RNG seeded
  Game();
  // Name - LoadSquadNamesFromFile()
  // Desc - Loads squad names for player and enemy from a text file
  // Preconditions - File with at least two lines exists
  // Postconditions - Sets m_playerSquadName and m_enemySquadName
  void LoadSquadNamesFromFile(string filename);
  // Name - Setup()
  // Desc - Creates units and assigns them to player and enemy squads
  // Preconditions - Squad names loaded
  // Postconditions - Player and enemy squads populated with members
  void Setup();
  // Name - Run()
  // Desc - Executes the battle loop until one squad is defeated
  // Preconditions - Squads are set up
  // Postconditions - Outputs turn-by-turn battle results and winner
  void Run();
 private:
  Squad m_playerSquad;   // Squad of units (Player)
  Squad m_enemySquad;    // Squad of units (Enemy)
  string m_playerSquadName; //Name of squad (Player)
  string m_enemySquadName; //Name of squad (Enemy)
};

#endif
